names = [
   "Definir una Función",
   "Listas en Python",
   "Tuplas y Secuencias",
   "Diccionarios en Python",
   "Sets",
   "Estructuras de Control de Flujo",
   "Sentencias Condicionales",
   "Bucles While",
   "Bucles For",
   "Funciones Lambda",
   "Manejo de Excepciones",
   "Clases y Objetos",
   "Herencia en Python",
   "Módulos en Python",
   "Entrada y Salida de Archivos",
   "Manejo de Argumentos de Línea de Comandos",
   "Expresiones Regulares",
   "Gestión de Fechas y Horas",
   "Operaciones de Sistema",
   "Interactuando con el Sistema Operativo",
]

